### PR TITLE
Update 2020

### PR DESCRIPTION
**Pull request by Yardboy**
Here's updates on everything to date. Missing just a couple of ball images that I'll send over asap, but this should get things current. Sorry I've been out of touch on getting these done in timely manner.

### CODE REVIEW

**Comment by cranst0n** [comment]
@Yardboy. Finally found a little time to review this. Aside from the missing Superstar ball images, LGTM. Are you still planning up pushing up those additions?

**Comment by Yardboy** [comment]
I completely forgot about that one - asking Vic for the images.

**Comment by Yardboy** [comment]
Hey, I took a swing at the ball images in PS just to get this update
pushed. I'm regen-ing now, will push update asa finished.

c.

**Comment by Yardboy** [comment]
Superstar ball images added.

**Comment by cranst0n** [comment]
Thank Cayce. Will merge this later today.

**Pull request merged**
