### PR TITLE
Dreaded Dunes

### PR DESCRIPTION
**Pull request by Yardboy**
Updates for Dreaded Dunes:

Add new balls Serpent and Werewolf

Add Dreaded Dunes course

Add Dreaded Dunes tournament

Add Dreaded Dunes notesheets

Replace Dreaded Dunes JPG course scenics with PNGs

Other Changes:

Update Coastal Classic image resize

Update typo in Silverstate tourney yaml

Add missing Monster Marsh announcement

Tweaked bin/dev and docker help file

Fix size of city of light banner sizing

### CODE REVIEW

**Comment by Yardboy** [comment]
Not sure why it pulled all those other commits in again - I rebased to dev  to try and squeeze everything down to one commit. I checked the files changed list and it all looks right.

**Comment by Yardboy** [comment]
Added Anubis and Scarab balls from Vic.

**Comment by cranst0n** [comment]
Thanks @Yardboy! Apologies for the delay in merging this. I'll try to be better in the future.

**Comment by Yardboy** [comment]
No worries. I have a fix to push up in a bit, Vic told me he had the wrong
image files for hole 7.

c.

**Pull request merged**
